//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiPathTeam.KeyboardExtension.Activities {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiPathTeam.KeyboardExtension.Activities.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Applies the input settings to the designated window. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ApplyDescription {
            get {
                return ResourceManager.GetString("ApplyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply Input Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ApplyDisplayName {
            get {
                return ResourceManager.GetString("ApplyDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Receives the result. True on success, False otherwise. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ApplyResultDescription {
            get {
                return ResourceManager.GetString("ApplyResultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ApplyResultDisplayName {
            get {
                return ResourceManager.GetString("ApplyResultDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Win32 Handle of a window to apply the input settings to. Window, Browser, and UiElement are also acceptable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ApplyWindowHandleDescription {
            get {
                return ResourceManager.GetString("ApplyWindowHandleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window Handle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ApplyWindowHandleDisplayName {
            get {
                return ResourceManager.GetString("ApplyWindowHandleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifies whether to block human keyboard input or not. True to block. False not to. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BlockKeyboardInputDescription {
            get {
                return ResourceManager.GetString("BlockKeyboardInputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Block Keyboard Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BlockKeyboardInputDisplayName {
            get {
                return ResourceManager.GetString("BlockKeyboardInputDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifies whether to block human mouse input or not. True to block. False not to. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BlockMouseInputDescription {
            get {
                return ResourceManager.GetString("BlockMouseInputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Block Mouse Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BlockMouseInputDisplayName {
            get {
                return ResourceManager.GetString("BlockMouseInputDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configures the input settings for the windows designated by the Apply Input Settings activity. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigureDescription {
            get {
                return ResourceManager.GetString("ConfigureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configure Input Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigureDisplayName {
            get {
                return ResourceManager.GetString("ConfigureDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preferred Keyboard Layout is not set while Force Keyboard Layout is set to True. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigureKeyboardLayoutArgumentValidationError {
            get {
                return ResourceManager.GetString("ConfigureKeyboardLayoutArgumentValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifies whether to forcibly turn off Input Method Editor or not. True to turn off. False not to. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DisableInputMethodEditorDescription {
            get {
                return ResourceManager.GetString("DisableInputMethodEditorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disable Input Method Editor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DisableInputMethodEditorDisplayName {
            get {
                return ResourceManager.GetString("DisableInputMethodEditorDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifies whether to force the preferred keyboard layout if available or not. True to force. False not to. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ForceKeyboardLayoutDescription {
            get {
                return ResourceManager.GetString("ForceKeyboardLayoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Force Keyboard Layout に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ForceKeyboardLayoutDisplayName {
            get {
                return ResourceManager.GetString("ForceKeyboardLayoutDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Receives the Conversion Mode compartment value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetStateConversionModeDescription {
            get {
                return ResourceManager.GetString("GetStateConversionModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Conversion Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetStateConversionModeDisplayName {
            get {
                return ResourceManager.GetString("GetStateConversionModeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gets the keyboard layout and the compartment values set in the designated window. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetStateDescription {
            get {
                return ResourceManager.GetString("GetStateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get Keyboard State に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetStateDisplayName {
            get {
                return ResourceManager.GetString("GetStateDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Receives the language ID of the keyboard layout. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetStateKeyboardLayoutDescription {
            get {
                return ResourceManager.GetString("GetStateKeyboardLayoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keyboard Layout に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetStateKeyboardLayoutDisplayName {
            get {
                return ResourceManager.GetString("GetStateKeyboardLayoutDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Receives the Keyboard OpenClose compartment value. True when IME is turned on. False otherwise. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetStateKeyboardOpenCloseDescription {
            get {
                return ResourceManager.GetString("GetStateKeyboardOpenCloseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keyboard OpenClose に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetStateKeyboardOpenCloseDisplayName {
            get {
                return ResourceManager.GetString("GetStateKeyboardOpenCloseDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Win32 Handle of a window to retrieve the keyboard state from. Window, Browser, and UiElement are also acceptble. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetStateWindowHandleDescription {
            get {
                return ResourceManager.GetString("GetStateWindowHandleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window Handle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GetStateWindowHandleDisplayName {
            get {
                return ResourceManager.GetString("GetStateWindowHandleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initializes the keyboard extension activity package. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InitializeDescription {
            get {
                return ResourceManager.GetString("InitializeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialize Keyboard Extension に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InitializeDisplayName {
            get {
                return ResourceManager.GetString("InitializeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputCategory {
            get {
                return ResourceManager.GetString("InputCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OutputCategory {
            get {
                return ResourceManager.GetString("OutputCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language ID of the preferred keyboard layout to be set if the Force Keyboard Layout property is set to True. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PreferredKeyboardLayoutDescription {
            get {
                return ResourceManager.GetString("PreferredKeyboardLayoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preferred Keyboard Layout に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PreferredKeyboardLayoutDisplayName {
            get {
                return ResourceManager.GetString("PreferredKeyboardLayoutDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restores the input settings for the UI elements designated by the Apply activity. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RestoreDescription {
            get {
                return ResourceManager.GetString("RestoreDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restore Input Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RestoreDisplayName {
            get {
                return ResourceManager.GetString("RestoreDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Win32 Handle of a window to restore. Window, Browser, and UiElement are also acceptable. If omitted, all applied windows will be restored. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RestoreWindowHandleDescription {
            get {
                return ResourceManager.GetString("RestoreWindowHandleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window Handle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RestoreWindowHandleDisplayName {
            get {
                return ResourceManager.GetString("RestoreWindowHandleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Conversion Mode compartment value to set. Specify either this or the Keyboard OpenClose compartment value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SetStateConversionModeDescription {
            get {
                return ResourceManager.GetString("SetStateConversionModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Conversion Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SetStateConversionModeDisplayName {
            get {
                return ResourceManager.GetString("SetStateConversionModeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sets one of compartment values of the keyboard to the designated window.  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SetStateDescription {
            get {
                return ResourceManager.GetString("SetStateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Keyboard State に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SetStateDisplayName {
            get {
                return ResourceManager.GetString("SetStateDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Both Keyboard OpenClose and Conversion Mode cannot be specified at the same time. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SetStateInputArgumentValidationError {
            get {
                return ResourceManager.GetString("SetStateInputArgumentValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keyboard OpenClose compartment value to set. Specify either this or the Conversion Mode compartment value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SetStateKeyboardOpenCloseDescription {
            get {
                return ResourceManager.GetString("SetStateKeyboardOpenCloseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keyboard OpenClose に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SetStateKeyboardOpenCloseDisplayName {
            get {
                return ResourceManager.GetString("SetStateKeyboardOpenCloseDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Receives the Conversion Mode compartment value previously set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SetStatePreviousConversionModeDescription {
            get {
                return ResourceManager.GetString("SetStatePreviousConversionModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous Conversion Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SetStatePreviousConversionModeDisplayName {
            get {
                return ResourceManager.GetString("SetStatePreviousConversionModeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Receives the Keyboard OpenClose compartment value previously set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SetStatePreviousKeyboardOpenCloseDescription {
            get {
                return ResourceManager.GetString("SetStatePreviousKeyboardOpenCloseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Previous Keyboard OpenClose に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SetStatePreviousKeyboardOpenCloseDisplayName {
            get {
                return ResourceManager.GetString("SetStatePreviousKeyboardOpenCloseDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Win32 Handle of the target window. Window, Browser, and UiElement are also acceptable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SetStateWindowHandleDescription {
            get {
                return ResourceManager.GetString("SetStateWindowHandleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window Handle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SetStateWindowHandleDisplayName {
            get {
                return ResourceManager.GetString("SetStateWindowHandleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifies the key combination to toggle on/off state of the input settings. Virtual key names are accepted. Plus sign combines keys. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToggleSequenceDescription {
            get {
                return ResourceManager.GetString("ToggleSequenceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toggle Sequence に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToggleSequenceDisplayName {
            get {
                return ResourceManager.GetString("ToggleSequenceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uninitializes the keyboard extension activity package. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UninitializeDescription {
            get {
                return ResourceManager.GetString("UninitializeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uninitialize Keyboard Extension に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UninitializeDisplayName {
            get {
                return ResourceManager.GetString("UninitializeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Null value cannot be specified to Window Handle (Window, Browser, or UiElement). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WindowHandleArgumentValidationError {
            get {
                return ResourceManager.GetString("WindowHandleArgumentValidationError", resourceCulture);
            }
        }
    }
}
